name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  packages: read

env:
  MISE_ENV: ci

jobs:
  Lint:
    name: Lint
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun install --frozen-lockfile
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run format:check
      - run: bun run spell
      - run: actionlint

  Test:
    name: Test
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun install --frozen-lockfile
      - run: bun test

  Build:
    name: Build
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun install --frozen-lockfile
      - run: bun run build

  commit-lint:
    name: Conventional Commits
    runs-on: [self-hosted, Linux, ARM64]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - env:
          FROM: ${{ github.event.pull_request.base.sha }}
          TO: ${{ github.event.pull_request.head.sha }}
        run: cog check "${FROM}..${TO}"
